name: CI Pipeline

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'


concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Composer version check
  composer-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      passed: ${{ steps.check.outcome }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up UV
        uses: astral-sh/setup-uv@v6

      - name: Check version in composer.json
        id: check
        run: |
          uv run python .github/scripts/check_version.py

  # Test job, runs only if composer check succeeds
  tests:
    needs: composer-check
    if: ${{ needs.composer-check.result == 'success' }}
    runs-on: ubuntu-latest
    environment: testing

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: xdebug

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Node Dependencies
        run: npm i

#      - name: Get installed Playwright version
#        id: playwright-version
#        run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package-lock.json').dependencies['@playwright/test'].version)")" >> $GITHUB_ENV
#      - name: Cache playwright binaries
#        uses: actions/cache@v3
#        id: playwright-cache
#        with:
#          path: |
#            ~/.cache/ms-playwright
#          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}
#
#      - run: npx playwright install --with-deps
#        if: steps.playwright-cache.outputs.cache-hit != 'true'
#      - run: npx playwright install-deps
#        if: steps.playwright-cache.outputs.cache-hit != 'true'

      - name: Add Flux Credentials Loaded From ENV
        run: composer config http-basic.composer.fluxui.dev "${{ secrets.FLUX_USERNAME }}" "${{ secrets.FLUX_LICENSE_KEY }}"

      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Build Assets
        run: npm run build

      - name: Run Tests
        run: ./vendor/bin/pest --ci --parallel --exclude-group=screenshot
